imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: en

framework:
  #esi: ~
  #translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  #validation: { enable_annotations: true }
  #serializer: { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale: '%locale%'
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
  fragments: ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true
  serializer:
      enabled: true

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    entity_managers:
      default:
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true


# Swiftmailer Configuration
swiftmailer:
  transport: '%mailer_transport%'
  host: '%mailer_host%'
  username: '%mailer_user%'
  password: '%mailer_password%'
  spool: { type: memory }

jms_di_extra:
  locations:
    all_bundles: false
    bundles: ['CoreBundle', 'ApiBundle']

fos_rest:
  disable_csrf_role: true
  view:
    view_response_listener: force
    formats:
      json: true
    mime_types:
      json:   ['application/json']
  body_listener: true
  param_fetcher_listener: force
  allowed_methods_listener: true
  zone:
    - { path: ^/api/* }
  format_listener:
    rules:
      - { path: ^/api/, priorities: [ json ], fallback_format: ~, prefer_extension: true }
      - { path: ^/, stop: true }
  routing_loader:
    default_format: json
  exception:
      enabled: true
      codes:
          'ApiBundle\Exception\DomainLogicException': 409
      messages:
          'ApiBundle\Exception\DomainLogicException': true

doctrine_migrations:
  dir_name: "%kernel.root_dir%/Migrations"
  namespace: App\Migrations

stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      timestampable: true
      softdeleteable: true

sensio_framework_extra:
  request:
    converters: true
    auto_convert: false

jms_serializer:
  metadata:
    cache: file
    debug: "%kernel.debug%"
    file_cache:
      dir: "%kernel.cache_dir%/serializer"
    directories:
      entity:
        namespace_prefix: CoreBundle\Entity
        path: '@CoreBundle/Resources/config/serializer/entity'
  handlers:
    datetime:
      default_format: 'c'